export const page = `<!doctype html><html lang="en"><meta charset="utf-8"><title>ESCALATE · Phantom signing check</title>
<style>body{font:18px system-ui;max-width:760px;margin:48px auto;padding:20px;line-height:1.5}button{padding:12px;margin:8px 8px 8px 0}pre{white-space:pre-wrap;background:#eee;padding:16px}</style>
<h1>Verify Phantom message signing</h1><p>This temporary local helper verifies one message signature. No transaction, Gibwork API request, funds or bounty operation will occur. Your wallet keeps all secrets.</p>
<button id="connect">1. Connect Phantom</button><button id="sign" disabled>2. Sign verification message</button><button id="disconnect" disabled>Disconnect</button>
<p id="status">Open in Brave, where your Phantom extension is installed.</p><pre id="message"></pre><script src="/bridge.js"></script></html>`;
export const browserScript = `
const session=location.hash.slice(1);history.replaceState(null,'',location.pathname);
const status=document.getElementById('status'), preview=document.getElementById('message');
const connect=document.getElementById('connect'), sign=document.getElementById('sign'), disconnect=document.getElementById('disconnect');
let provider=null, publicKey=null, message=null;
async function api(path,options={}) {const response=await fetch(path,{...options,headers:{'x-escalate-session':session,...options.headers}});const data=await response.json();if(!response.ok)throw new Error(data.error || 'Session expired');return data;}
connect.onclick=async()=>{try {connect.disabled=true;provider=window.phantom?.solana;if(!provider?.isPhantom)throw new Error('Phantom is not available. Open this page as a top-level Brave tab with the extension enabled.');const connected=await provider.connect();publicKey=connected.publicKey.toString();message=(await api('/challenge')).message;preview.textContent=message;status.textContent='Connected. Review the exact message below, then click Sign verification message.';sign.disabled=false;disconnect.disabled=false;provider.on('accountChanged',()=>{sign.disabled=true;status.textContent='Wallet account changed. Stop this session and start a new signing check.';});provider.on('disconnect',()=>{sign.disabled=true;status.textContent='Wallet disconnected. Start a new signing check.';});}catch(error){status.textContent=error.code===4001?'Connection rejected. No signature requested.':error.message;connect.disabled=false;}};
sign.onclick=async()=>{try {sign.disabled=true;if(provider.publicKey?.toString()!==publicKey)throw new Error('Wallet changed. Restart this session.');const signed=await provider.signMessage(new TextEncoder().encode(message),'utf8');if((signed.publicKey && signed.publicKey.toString()!==publicKey) || provider.publicKey?.toString()!==publicKey)throw new Error('Wallet changed. Signature not submitted.');const signature=Array.from(signed.signature);await api('/signature',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({publicKey,signature})});status.textContent='Verified by ESCALATE. No Gibwork request was sent. You may disconnect Phantom and close this tab.';publicKey=null;message=null;}catch(error){status.textContent=error.code===4001?'Signature rejected. Nothing was submitted.':error.message;sign.disabled=false;}};
disconnect.onclick=async()=>{try{await provider.disconnect();publicKey=null;message=null;sign.disabled=true;disconnect.disabled=true;status.textContent='Disconnected. Close this tab.';}catch{status.textContent='Disconnect using Phantom Connected Apps if needed.';}};
`;

export const livePage = page.replace('Phantom signing check','Gibwork read-only authentication').replace('Verify Phantom message signing','Authenticate one Gibwork read').replace('This temporary local helper verifies one message signature. No transaction, Gibwork API request, funds or bounty operation will occur.', 'Approve the exact SDK authentication message for one GET of available tasks (page 1, limit 1). No transaction, funds or bounty operation will occur.').replace('Sign verification message','Sign Gibwork read authentication');
export const liveBrowserScript = browserScript.replace("api('/challenge')", "api('/challenge?publicKey='+encodeURIComponent(publicKey))").replaceAll('Sign verification message','Sign Gibwork read authentication').replace('No Gibwork request was sent.', 'One Gibwork read is now being attempted; check Terminal for its result.').replace('sign.disabled=false;}};', 'sign.disabled=true;}};');
